server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP Firefox 10"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "10.0"
    "os": "windows"
    "os_version": "xp"